<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>AreaCut.Media</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AreaCut.Core\AreaCut.Core.csproj" />
  </ItemGroup>

</Project>